### ISSUE TITLE
FULivePC nodejs调用c++启动摄像头失败

### ISSUE THREAD

**Issue by jasonsalex** [Faceunity/FULivePC#1]
js调用c++的时候, 在nama:init函数的m_cap->OpenCamera函数返回false,一直无法启动摄像头
原版的demo正常,是不是nodejs无法调用底层接口

**Comment by vimgaa** [comment]
nodejs 调用c++然后c++使用ds是可以打开摄像头的，出现打开失败的问题，可以在失败处打断点，看程序所需的环境是否成功初始化。
